package com.shah.moneybasetask.domain.model.stock_summary

data class SummaryDetail(
    val ask: Ask = Ask(),
    val averageDailyVolume10Day: AverageDailyVolume10Day = AverageDailyVolume10Day(),
    val averageVolume: AverageVolume = AverageVolume(),
    val averageVolume10days: AverageVolume10days = AverageVolume10days(),
    val bid: Bid = Bid(),
    val circulatingSupply: CirculatingSupply = CirculatingSupply(),
    val coinMarketCapLink: String = "",
    val currency: String = "",
    val dayHigh: DayHigh = DayHigh(),
    val dayLow: DayLow = DayLow(),
    val fiftyDayAverage: FiftyDayAverage = FiftyDayAverage(),
    val fiftyTwoWeekHigh: FiftyTwoWeekHigh = FiftyTwoWeekHigh(),
    val fiftyTwoWeekLow: FiftyTwoWeekLow = FiftyTwoWeekLow(),
    val fromCurrency: String = "",
    val lastMarket: String = "",
    val marketCap: MarketCap = MarketCap(),
    val `open`: Open = Open(),
    val previousClose: PreviousClose = PreviousClose(),
    val priceHint: PriceHint = PriceHint(),
    val regularMarketDayHigh: RegularMarketDayHigh = RegularMarketDayHigh(),
    val regularMarketDayLow: RegularMarketDayLow = RegularMarketDayLow(),
    val regularMarketOpen: RegularMarketOpen = RegularMarketOpen(),
    val regularMarketPreviousClose: RegularMarketPreviousClose = RegularMarketPreviousClose(),
    val regularMarketVolume: RegularMarketVolume = RegularMarketVolume(),
    val startDate: StartDate = StartDate(),
    val toCurrency: String = "",
    val twoHundredDayAverage: TwoHundredDayAverage = TwoHundredDayAverage(),
    val volume: Volume = Volume(),
    val volume24Hr: Volume24Hr = Volume24Hr(),
    val volumeAllCurrencies: VolumeAllCurrencies = VolumeAllCurrencies()
)